### ISSUE TITLE
번역 질문.

### ISSUE THREAD

**Issue by devarchi33** [EngForDev/awesome-engfordev#6]
안녕하세요 :)

이곳에 이렇게 질문을 드려도 되는지 모르겠지만 도움을 딱히 구할 곳이 없어서 올려보아요;;

BTrace 라는 java trace tool 의 [User Guide](https://kenai.com/projects/btrace/pages/UserGuide) 를 번역해보고 있는데

> Trace  statements that are executed whenever a probe "fires". 

 구문을  저는 "실행되는 추적 구문들은 언제든지 중단할 수 있다." 라고 번역했는데 

영 어색하네요;;;;

어떻게 바꾸면 좋을까요?

**Comment by LucyJeong** [comment]
안녕하세요 이슈가 올라와서 깜짝놀랐네요 😁

> Trace statements that are executed whenever a probe "fires".

여기 따음표로 되어있는 fire는 또 다른 뜻을 갖고 있는 것 같은데 혹 어떠한 용어인가요?
그리고 추가질문 ✋ 혼자 번역하고 계신건지 궁금합니다!

**Comment by devarchi33** [comment]
"fire" 는 저도 정확히는 모르겠지만 sample 코드를 돌려본 느낌으로는 
코드를 추적할 때, 추적할 지점에 도착한 것을 말하는 것 같습니다.

방금 시작해서 혼자 하고 있어요 ㅎㅎ 

https://github.com/devarchi33/BTrace-document-translation

**Comment by nassol** [comment]
저는 이렇게 이해했습니다.

"probe가 fire될 때마다 실행되는 구문들을 추적하세요"

probe의 의미를 짚으시는 것이 필요할 듯 하네용

probe:
http://searchsecurity.techtarget.com/definition/probe

fire는 무언가가 발화되다 이런 뜻도 있는데 여기에서는 probe라는 것이 실행하도록 "촉발되었을 때" 이런 의미가 아닐까 합니다.

총을 생각해보죠. 방아쇠를 당기면 (pull the trigger)
총알이 발사되다 (the gun fires)

**Comment by nassol** [comment]
번역하시다가 막히시는 부분이 있으시면 개발자 영어 페이스북 그룹에 올리시면 도움을 받을 수 있을 거에요~

**Comment by nassol** [comment]
아 어떤 것을 설명하는 것이네요.

그렇다면 trace는 추적하세요..가 아니라 추적한다..로 이해하는 것이 맞을 것 같아요

**Comment by LucyJeong** [comment]
> Trace statements that are executed whenever a probe "fires".

종합해보자면, **probe가 촉발 될 때마다 실행되는 구문들을 추적한다.** 

번역하시는거 [여기](https://github.com/EngForDev/awesome-engfordev/blob/master/whenYouSeeTutorial/README.md) 에서 함께 하면 좋을 것 같네요 😄

**Comment by devarchi33** [comment]
"fire" 가 달리기 시작 할 때, 권총을 발사하는 행위 같은 거군요 "요이땅" 같은..후

@nassol @LucyJeong 감사합니다!
